name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      if: false
      with:
        go-version: 1.20.x
      id: go

    - name: Build go from tip
      if: false
      uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.go_arch }} GOROOT_FINAL=/
        test_build: true

    - name: Docker commands
      run: |
        docker run -t -rm --privileged multiarch/qemu-user-static:mips64el uname -m
        docker run -d -t --platform mips64le --name xalpine mips64le/debian
        docker exec xalpine mkdir -p /tmp/go/src/cmd/go/
        docker exec xalpine uname
