name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      if: false
      with:
        go-version: 1.22.x
      id: go

    - uses: actions/checkout@v4
    - uses: iwdgo/gotip-build@master
      id: gotip
      if: false
      with:
        go_variables: GOOS=freebsd
        test_build: 'false'
    - name: Test in FreeBSD
      run: |
        pkg install -y socat
        https://download:freebsd:org/ftp/releases/VM-IMAGES/14:1-RELEASE/amd64/Latest/:
        qemu-system-x86_64 -m 2048 \
         -hda FreeBSD-14.1-RELEASE-amd64.qcow2 -enable-kvm \
         -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 \
         -device e1000,netdev=mynet0
        sshd_enable="YES"
        ifconfig_em0="DHCP"
        service netif restart
        service sshd start
        ssh -p 7722 root@localhost
