name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

      - name: Set up Go
        if: false
        uses: actions/setup-go@v4

      - name: Vbox
        shell: bash
        run: |
          vboxmanage -v
          # Extension pack
          wget https://download.virtualbox.org/virtualbox/6.1.38/Oracle_VM_VirtualBox_Extension_Pack-6.1.38.vbox-extpack
          echo y | sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-6.1.38.vbox-extpack
          # 
          wget -nv https://download.freebsd.org/releases/VM-IMAGES/13.2-RELEASE/amd64/Latest/FreeBSD-13.2-RELEASE-amd64.vhd.xz
          xz -d FreeBSD-13.2-RELEASE-amd64.vhd.xz
          # wget -nv https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/13.2/FreeBSD-13.2-RELEASE-amd64-disc1.iso
          ls -l
          VBoxManage createvm --name xcompile --ostype FreeBSD_64 --default --register
          # VBoxManage list vms --long
          VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type hdd --medium FreeBSD-13.2-RELEASE-amd64.vhd
          # VBoxManage unattended install xcompile --install-additions
          # VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type dvddrive --medium FreeBSD-13.2-RELEASE-amd64-disc1.iso
          # VBoxManage list ostypes
          # cat '/Users/runner/VirtualBox VMs/xcompile/xcompile.vbox'
          # Configuration
          # netstat -ntlp | grep -i ssh
          # Set up
          # VBoxManage natnetwork add --netname natnet1 --network "192.168.15.0/24" --enable
          # VBoxManage modifyvm xcompile --natpf1 "ssh,tcp,127.0.0.1,3022,192.168.15.0,22"
          VBoxManage modifyvm xcompile --natpf1 "ssh,tcp,,3022,,22"
          # Management
          VBoxManage showvminfo xcompile
          VBoxManage startvm xcompile --type headless
          echo "list vms" $(VBoxManage list vms)
          VBoxManage guestproperty enumerate xcompile
          # VBoxManage debugvm xcompile logdest stdout
          ### Use ssh
          sshpass -p root ssh -v -T -p 3022 root@127.0.0.1 "bash pwd"
          root
          #### No guest facility available
          # 
          # sleep 60
          # https://docs.freebsd.org/en/books/handbook/virtualization/#virtualization-guest-virtualbox
          # No guest facilities installed
          # VBoxManage guestcontrol xcompile run --exe "cd /usr/ports/emulators/virtualbox-ose-additions && make install clean"
          
          # Restart
          # VBoxManage controlvm xcompile savestate
          # VBoxManage startvm xcompile --type headless 
          # Smoke tests
          # VBoxManage guestcontrol xcompile run --exe "/bin/ls"
          # VBoxManage guestcontrol xcompile run --exe "/bin/uname -a"
          
