name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

      - name: Set up Go
        if: false
        uses: actions/setup-go@v4

      - name: Vbox
        shell: bash
        run: |
          vboxmanage -v
          # Extension pack
          # wget https://download.virtualbox.org/virtualbox/6.1.34/Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack
          # echo y | sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack
          wget -nv https://download.freebsd.org/releases/VM-IMAGES/13.2-RELEASE/amd64/Latest/FreeBSD-13.2-RELEASE-amd64.vhd.xz
          xz -d FreeBSD-13.2-RELEASE-amd64.vhd.xz
          # wget -nv https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/13.2/FreeBSD-13.2-RELEASE-amd64-disc1.iso
          ls -l
          VBoxManage createvm --name xcompile --ostype FreeBSD_64 --default --register
          # VBoxManage list vms --long
          VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type hdd --medium FreeBSD-13.2-RELEASE-amd64.vhd
          # VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type dvddrive --medium FreeBSD-13.2-RELEASE-amd64-disc1.iso
          # VBoxManage list ostypes
          VBoxManage startvm xcompile # --type headless
          VBoxManage debugvm xcompile logdest stdout
          # Management
          echo "list vms" $(VBoxManage list vms)
          VBoxManage showvminfo xcompile
          echo "Guest control"
          # https://docs.freebsd.org/en/books/handbook/virtualization/#virtualization-guest-virtualbox
          # No guest facilities installed
          VBoxManage guestcontrol xcompile run --exe "cd /usr/ports/emulators/virtualbox-ose-additions && make install clean"
          
          # Restart
          VBoxManage controlvm xcompile savestate
          VBoxManage startvm xcompile --type headless 
          # Smoke tests
          VBoxManage guestcontrol xcompile run --exe "/bin/ls"
          VBoxManage guestcontrol xcompile run --exe "/bin/uname -a"
          
