name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@v0.2.0
      id: gotip
      with:
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      with:
        name: gotip-${{ runner.os }}-${{ runner.arch }}
        path: go/bin
