name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      if: true
      with:
        go-version: 1.22.x
      id: go

    - uses: actions/checkout@v4
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - uses: iwdgo/gotip-build@master
      id: gotip
      if: false
      with:
        go_variables: GOOS=freebsd
        test_build: 'false'
    - name: Test in FreeBSD
      run: |
        sudo apt install qemu-system-x86
        # Download freebsd
        wget https://download.freebsd.org/ftp/releases/VM-IMAGES/14.1-RELEASE/amd64/Latest/FreeBSD-14.1-RELEASE-amd64.qcow2.xz
        xz --decompress FreeBSD-14.1-RELEASE-amd64.qcow2.xz
        # Provision the image
        # qemu-img create -f qcow2 -F qcow2 -b FreeBSD-14.1-RELEASE-amd64.qcow2 freebsd.qcow2 +1G
        # ps -ef | grep qemu-system-x86_64
        # Start
        systemctl enable serial-getty@ttyS0.service
        qemu-system-x86_64 -m 2048 \
          -hda FreeBSD-14.1-RELEASE-amd64.qcow2 -enable-kvm \
          -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 \
          -device e1000,netdev=mynet0 \
          -nographic \
          -serial unix:console.sock,server,nowait
          console=ttyS0,38400n8 earlyprint=serial,ttyS0,38400n8 \
          freebsd.qcow2 +1G
        uname -a
        socat STDIO,cfmakeraw UNIX:console.sock
        # Enter Freebsd
        ssh -p 7722 root@localhost
        uname -a
        sysrc sshd_enable="YES" ifconfig_em0="DHCP"
        sed -i '$a PermitRootLogin prohibit-password" /etc/ssh/sshd.conf
        pkg install -y socat # freebsd package
        service netif restart
        service sshd start
        ls -la
        pwd
