name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@remove-qemu-setup
      id: gotip
      with:
        go_variables: CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 GOROOT_FINAL=/
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'true' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.arch }}
        path: go/bin/
