name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Docker
      run: |
        # /usr/bin/docker run --rm --privileged chainguard/dragonfly --install
        # /usr/bin/docker run -d -t --platform amd64 -e GOROOT=/tmp/go -e GO_TEST_TIMEOUT_SCALE=8 -e GOSUMDB=sum.golang.org --name xalpine chainguard/dragonfly
        docker pull chainguard/dragonfly:sha256-a7d3f79aeabc6882b5866e35b27582a5d6d798bbb8495e17407e30f1a64ff674.sig
