name: android
on:
  push:
    branches:
      - 'android'
    paths:
      - 'action.yml'
      - '.github/workflows/go.yml'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
        id: go

      - uses: gradle/gradle-build-action@v2
        id: add-gradle

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        id: setup-gradle

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Load emulator and smoke test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            gradle --version
            ls -l $NDK_ROOT/
            # gradle projects

      - name: Build go from tip
        uses: iwdgo/gotip-build@master
        id: gotip
        with:
          go_variables: GOOS=android GOARCH=arm64 CGO_ENABLED=1 CC=$NDK_ROOT/29.*/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang go build
          test_build: true
