name: go-on-tip
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go_arch: [386]
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: GOOS=linux GOARCH=${{ matrix.go_arch }}
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'false' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'true' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/${{ env.goos }}_${{ env.goarch }}
