name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Docker
      run: |
        /usr/bin/docker run -d -t --platform amd64 -e GOROOT=/tmp/go -e GO_TEST_TIMEOUT_SCALE=8 -e GOSUMDB=sum.golang.org --name xalpine chainguard/dragonfly
        
