name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
      id: go

    - uses: actions/checkout@v4
    - uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: GOOS=netbsd
        test_build: 'false'
    - name: Test in netbsd
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg install -y socat

        run: |
          if [ -n "test" ]; then
            echo "false"
          fi
          if [ "test" ]; then
            echo "test"
          fi
          pwd
          cat go/go.env
          whoami
          env
          uname -a
          echo "OK"
          # go test
          cd go/src
          ../bin/netbsd_amd64/go version
          ../bin/netbsd_amd64/go env
          cp ../bin/netbsd_amd64/go ../bin/go
          cp ../bin/netbsd_amd64/gofmt ../bin/gofmt
          ../bin/go tool dist test
