name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

      - name: Set up Go
        if: false
        uses: actions/setup-go@v4

      - name: Vbox
        shell: bash
        run: |
          vboxmanage -v
          VBoxManage list ostypes
          wget -nv https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.3/images/NetBSD-9.3-amd64.iso
          ls -l
          VBoxManage createvm --name xcompile --ostype NetBSD_64 --default --register
          # VBoxManage list vms --long
          # VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type hdd --medium FreeBSD-13.2-RELEASE-amd64.vhd
          VBoxManage storageattach xcompile --storagectl IDE --port 0 --device 0 --type dvddrive --medium NetBSD-9.3-amd64.iso
          # VBoxManage list ostypes
          VBoxManage startvm xcompile # --type headless
          VBoxManage debugvm xcompile logdest stdout
          # Management
          echo "list vms" $(VBoxManage list vms)
          VBoxManage showvminfo xcompile
          VBoxManage guestproperty enumerate xcompile
          # https://docs.freebsd.org/en/books/handbook/virtualization/#virtualization-guest-virtualbox
          # No guest facilities installed
          VBoxManage guestcontrol xcompile run --exe "cd /usr/ports/emulators/virtualbox-ose-additions && make install clean"
          
          # Restart
          VBoxManage controlvm xcompile savestate
          VBoxManage startvm xcompile --type headless 
          # Smoke tests
          VBoxManage guestcontrol xcompile run --exe "/bin/ls"
          VBoxManage guestcontrol xcompile run --exe "/bin/uname -a"
          
