name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - uses: actions/checkout@v4
    - uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: GOOS=freebsd
        test_build: 'false'
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        # envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg install -y socat

        run: |
          if [ -n "test" ]; then
            echo "false"
          fi
          if [ "test" ]; then
            echo "test"
          fi
          pwd
          ls -lah
          ls -lah go
          whoami
          env
          uname -a
          echo "OK"
          # go test
          cd go/src
          ../bin/go version
          ../bin/go env
          ../bin/go tool dist test
