name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      if: false
      with:
        go-version: 1.20.x
      id: go

    - name: Build go from tip
      if: false
      uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.go_arch }} GOROOT_FINAL=/
        test_build: true

    - name: Docker commands
      run: |
        docker pull multiarch/qemu-user-static:mips64el
        docker run -d -t --privileged --platform mips64le --name xcompile mips64le/debian
