name: macos
on:
  push:
    branches:
      - 'issue30136'
    paths:
      - '0001-cmd-go-return-error-when-directory-has-no-go.mod-in-.patch'
      - '.github/workflows/macos.yml'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Get patch files
      uses: actions/checkout@v4

    - name: Build go from tip
      uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: GO_TEST_SHORT=0 GO_TEST_TIMEOUT_SCALE=5

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'false' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'true' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/${{ env.goos }}_${{ env.goarch }}
